export const TELEGRAM_SETTINGS_ID = "default";

export const TELEGRAM_CATEGORIES = Object.freeze({
  ORDER: "ORDER",
  TICKET: "TICKET",
  PAYMENT: "PAYMENT",
  FULFILLMENT: "FULFILLMENT",
});

export const TELEGRAM_EVENTS = Object.freeze({
  ORDER_PAID: "ORDER_PAID",
  ORDER_DELIVERED: "ORDER_DELIVERED",
  ORDER_STATUS_CHANGED: "ORDER_STATUS_CHANGED",
  TICKET_CREATED: "TICKET_CREATED",
  TICKET_CUSTOMER_REPLY: "TICKET_CUSTOMER_REPLY",
  PAYMENT_INITIATION_FAILED: "PAYMENT_INITIATION_FAILED",
  PAYMENT_VERIFICATION_FAILED: "PAYMENT_VERIFICATION_FAILED",
  PAYMENT_RECONCILIATION_FAILED: "PAYMENT_RECONCILIATION_FAILED",
  PAYMENT_FAILED: "PAYMENT_FAILED",
  PAYMENT_REVIEW_REQUIRED: "PAYMENT_REVIEW_REQUIRED",
  SHAREBOX_REVIEW_REQUIRED: "SHAREBOX_REVIEW_REQUIRED",
});
